## Application
spring:
  application:
    name: Tenpo Test
  profiles:
    active: dev
  datasource:   
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tenpo}?currentSchema=${DB_SCHEMA:tenpo}
    username: ${DB_USER:fabio}
    password: ${DB_PASS:fabio}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5001

## Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    filter: false

## Resilience
resilience4j:
  ratelimiter:
    instances:
      global:
        limitForPeriod: 3
        limitRefreshPeriod: 60s       
        timeoutDuration: 0s
  retry:
    instances:
      percentService:
        maxAttempts: 3
        waitDuration: 2s